INSERT INTO nopk.t1 VALUES (1, NULL, 100);
UPDATE nopk.t1 SET c = 200 WHERE a = 1 AND b IS NULL AND c = 100;
DELETE FROM nopk.t1;

INSERT INTO nopk.t2 VALUES (1, NULL, NULL, 100);
UPDATE nopk.t2 SET d = 200 WHERE a = 1 AND b IS NULL AND c IS NULL AND d = 100;
DELETE FROM nopk.t2;

INSERT INTO nopk.t3 VALUES (NULL, 2, 3);
UPDATE nopk.t3 SET c = 30 WHERE a IS NULL AND b = 2 AND c = 3;
UPDATE nopk.t3 SET c = NULL WHERE a IS NULL AND b = 2 AND c = 30;
DELETE FROM nopk.t3;