use test_db_1

-- 1000 rows are dynamically generated by test runner via run_cdc_check_large_data_test()
-- Each row: db.check_large_test.insertOne({_id: i, name: "user_i", value: i*100})
-- This produces 1000 independent CDC events (batch_size=100, so 10 batches)
