[net]
git-fetch-with-cli = true

# NOTES: `cargo search` will not work as crates source has been overwritten, need to specify `--registry` flag, 
# i.e., `cargo search <CRATE> --registry crates-io` 
[source.crates-io]
# replace-with = 'ustc'

[source.ustc]
# requires cargo 1.68+ to enable sparse index
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"
#registry = "https://mirrors.ustc.edu.cn/crates.io-index"


[target.x86_64-unknown-linux-musl]
# linker = "rust-lld"
linker = "x86_64-linux-musl-gcc"
# rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-unknown-linux-musl]
# linker = "rust-lld"
linker = "aarch64-linux-musl-gcc"
# rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-unknown-linux-gnu]
# linker = "rust-lld"
linker = "x86_64-linux-gnu-gcc"
# fix link error for https://github.com/briansmith/ring, refer to: https://github.com/briansmith/ring/issues/1605#issuecomment-1533940670
# rustflags = ["-C", "link-args=-fstack-protector-all -lssp"]
# rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-unknown-linux-gnu]
# linker = "rust-lld"
linker = "aarch64-linux-gnu-gcc"
# rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-pc-windows-msvc]
rustflags  =  ["-C", "target-feature=+crt-static"]