USE [ape_dts];
GO
DROP TABLE IF EXISTS [ape_dts].test_db_1.one_pk_no_uk_1;
DROP TABLE IF EXISTS [ape_dts].test_db_1.one_pk_no_uk_2;
DROP TABLE IF EXISTS [ape_dts].test_db_2.one_pk_no_uk_1;
DROP TABLE IF EXISTS [ape_dts].test_db_2.one_pk_no_uk_2;
DROP TABLE IF EXISTS [ape_dts].test_db_3.one_pk_no_uk_1;
DROP TABLE IF EXISTS [ape_dts].test_db_3.one_pk_no_uk_2;
DROP TABLE IF EXISTS [ape_dts].test_db_4.one_pk_no_uk_1;
DROP TABLE IF EXISTS [ape_dts].test_db_4.one_pk_no_uk_2;
DROP TABLE IF EXISTS [ape_dts].test_db_5.one_pk_no_uk_1;
DROP TABLE IF EXISTS [ape_dts].test_db_5.one_pk_no_uk_2;
DROP TABLE IF EXISTS [ape_dts].other_test_db_1.one_pk_no_uk_1;
DROP TABLE IF EXISTS [ape_dts].other_test_db_1.one_pk_no_uk_2;
DROP TABLE IF EXISTS [ape_dts].wild_a.keep_orders;
DROP TABLE IF EXISTS [ape_dts].wild_a.keep_private;
DROP TABLE IF EXISTS [ape_dts].wild_a.skip_orders;
DROP TABLE IF EXISTS [ape_dts].wild_b.keep_orders;
DROP TABLE IF EXISTS [ape_dts].wild_skip.keep_orders;
DROP TABLE IF EXISTS [filter_db_keep].dbo.db_level_kept;
DROP TABLE IF EXISTS [filter_db_skip].dbo.db_level_filtered;
DROP TABLE IF EXISTS [ape_dts].filter_schema_keep.schema_level_kept;
DROP TABLE IF EXISTS [ape_dts].filter_schema_skip.schema_level_filtered;

IF SCHEMA_ID(N'test_db_1') IS NULL EXEC(N'CREATE SCHEMA test_db_1');
IF SCHEMA_ID(N'test_db_2') IS NULL EXEC(N'CREATE SCHEMA test_db_2');
IF SCHEMA_ID(N'test_db_3') IS NULL EXEC(N'CREATE SCHEMA test_db_3');
IF SCHEMA_ID(N'test_db_4') IS NULL EXEC(N'CREATE SCHEMA test_db_4');
IF SCHEMA_ID(N'test_db_5') IS NULL EXEC(N'CREATE SCHEMA test_db_5');
IF SCHEMA_ID(N'other_test_db_1') IS NULL EXEC(N'CREATE SCHEMA other_test_db_1');
IF SCHEMA_ID(N'filter_schema_keep') IS NULL EXEC(N'CREATE SCHEMA filter_schema_keep');
IF SCHEMA_ID(N'filter_schema_skip') IS NULL EXEC(N'CREATE SCHEMA filter_schema_skip');

CREATE TABLE [ape_dts].test_db_1.one_pk_no_uk_1 (id int NOT NULL PRIMARY KEY, value decimal(20, 8) NULL, text_value nvarchar(50) NULL, binary_value varbinary(16) NULL);
CREATE TABLE [ape_dts].test_db_1.one_pk_no_uk_2 (id int NOT NULL PRIMARY KEY, value decimal(20, 8) NULL, text_value nvarchar(50) NULL, binary_value varbinary(16) NULL);
CREATE TABLE [ape_dts].test_db_2.one_pk_no_uk_1 (id int NOT NULL PRIMARY KEY, value decimal(20, 8) NULL, text_value nvarchar(50) NULL, binary_value varbinary(16) NULL);
CREATE TABLE [ape_dts].test_db_2.one_pk_no_uk_2 (id int NOT NULL PRIMARY KEY, value decimal(20, 8) NULL, text_value nvarchar(50) NULL, binary_value varbinary(16) NULL);
CREATE TABLE [ape_dts].test_db_3.one_pk_no_uk_1 (id int NOT NULL PRIMARY KEY, value decimal(20, 8) NULL, text_value nvarchar(50) NULL, binary_value varbinary(16) NULL);
CREATE TABLE [ape_dts].test_db_3.one_pk_no_uk_2 (id int NOT NULL PRIMARY KEY, value decimal(20, 8) NULL, text_value nvarchar(50) NULL, binary_value varbinary(16) NULL);
CREATE TABLE [ape_dts].test_db_4.one_pk_no_uk_1 (id int NOT NULL PRIMARY KEY, value decimal(20, 8) NULL, text_value nvarchar(50) NULL, binary_value varbinary(16) NULL);
CREATE TABLE [ape_dts].test_db_4.one_pk_no_uk_2 (id int NOT NULL PRIMARY KEY, value decimal(20, 8) NULL, text_value nvarchar(50) NULL, binary_value varbinary(16) NULL);
CREATE TABLE [ape_dts].test_db_5.one_pk_no_uk_1 (id int NOT NULL PRIMARY KEY, value decimal(20, 8) NULL, text_value nvarchar(50) NULL, binary_value varbinary(16) NULL);
CREATE TABLE [ape_dts].test_db_5.one_pk_no_uk_2 (id int NOT NULL PRIMARY KEY, value decimal(20, 8) NULL, text_value nvarchar(50) NULL, binary_value varbinary(16) NULL);
CREATE TABLE [ape_dts].other_test_db_1.one_pk_no_uk_1 (id int NOT NULL PRIMARY KEY, value decimal(20, 8) NULL, text_value nvarchar(50) NULL, binary_value varbinary(16) NULL);
CREATE TABLE [ape_dts].other_test_db_1.one_pk_no_uk_2 (id int NOT NULL PRIMARY KEY, value decimal(20, 8) NULL, text_value nvarchar(50) NULL, binary_value varbinary(16) NULL);
CREATE TABLE [filter_db_keep].dbo.db_level_kept (id int NOT NULL PRIMARY KEY, value nvarchar(80) NULL);
CREATE TABLE [filter_db_skip].dbo.db_level_filtered (id int NOT NULL PRIMARY KEY, value nvarchar(80) NULL);
CREATE TABLE [ape_dts].filter_schema_keep.schema_level_kept (id int NOT NULL PRIMARY KEY, value nvarchar(80) NULL);
CREATE TABLE [ape_dts].filter_schema_skip.schema_level_filtered (id int NOT NULL PRIMARY KEY, value nvarchar(80) NULL);
GO
