USE [ape_dts];
GO
DROP TABLE IF EXISTS [ape_dts].[test_db_*.*].[one_pk_no_uk_1_*.*];
DROP TABLE IF EXISTS [ape_dts].[test_db_*.*].[one_pk_no_uk_2_*.*];
DROP TABLE IF EXISTS [ape_dts].[test_db_&.&].[one_pk_no_uk_1_&.&];
DROP TABLE IF EXISTS [ape_dts].[test_db_&.&].[one_pk_no_uk_2_&.&];
DROP TABLE IF EXISTS [ape_dts].[test_db_^.^].[one_pk_no_uk_1_^.^];
DROP TABLE IF EXISTS [ape_dts].[test_db_^.^].[one_pk_no_uk_2_^.^];
DROP TABLE IF EXISTS [ape_dts].[test_db_@.@].[one_pk_no_uk_1_@.@];
DROP TABLE IF EXISTS [ape_dts].[test_db_@.@].[one_pk_no_uk_2_@.@];
DROP TABLE IF EXISTS [ape_dts].[*.*_test_db].[one_pk_no_uk_1_*.*];
DROP TABLE IF EXISTS [ape_dts].[*.*_test_db].[one_pk_no_uk_2_*.*];
DROP TABLE IF EXISTS [ape_dts].[&.&_test_db].[one_pk_no_uk_1_&.&];
DROP TABLE IF EXISTS [ape_dts].[&.&_test_db].[one_pk_no_uk_2_&.&];
DROP TABLE IF EXISTS [ape_dts].[^.^_test_db].[one_pk_no_uk_1_^.^];
DROP TABLE IF EXISTS [ape_dts].[^.^_test_db].[one_pk_no_uk_2_^.^];
DROP TABLE IF EXISTS [ape_dts].[@.@_test_db].[one_pk_no_uk_1_@.@];
DROP TABLE IF EXISTS [ape_dts].[@.@_test_db].[one_pk_no_uk_2_@.@];
DROP TABLE IF EXISTS [ape_dts].[special.* schema].[orders.* detail];
DROP TABLE IF EXISTS [mssql_filter.db_*_e2e].dbo.[db level.* kept];
DROP TABLE IF EXISTS [mssql_filter.db_1_e2e].dbo.[db level.* filtered];
DROP TABLE IF EXISTS [mssql_filter.ignore&db_e2e].dbo.[db level& ignored];
DROP TABLE IF EXISTS [ape_dts].[filter.schema_*].[schema level.* kept];
DROP TABLE IF EXISTS [ape_dts].[filter.schema_1].[schema level.* filtered];
DROP TABLE IF EXISTS [ape_dts].[filter.ignore?schema].[schema level? ignored];

IF SCHEMA_ID(N'test_db_*.*') IS NULL EXEC(N'CREATE SCHEMA [test_db_*.*]');
IF SCHEMA_ID(N'test_db_&.&') IS NULL EXEC(N'CREATE SCHEMA [test_db_&.&]');
IF SCHEMA_ID(N'test_db_^.^') IS NULL EXEC(N'CREATE SCHEMA [test_db_^.^]');
IF SCHEMA_ID(N'test_db_@.@') IS NULL EXEC(N'CREATE SCHEMA [test_db_@.@]');
IF SCHEMA_ID(N'*.*_test_db') IS NULL EXEC(N'CREATE SCHEMA [*.*_test_db]');
IF SCHEMA_ID(N'&.&_test_db') IS NULL EXEC(N'CREATE SCHEMA [&.&_test_db]');
IF SCHEMA_ID(N'^.^_test_db') IS NULL EXEC(N'CREATE SCHEMA [^.^_test_db]');
IF SCHEMA_ID(N'@.@_test_db') IS NULL EXEC(N'CREATE SCHEMA [@.@_test_db]');
IF SCHEMA_ID(N'filter.schema_*') IS NULL EXEC(N'CREATE SCHEMA [filter.schema_*]');
IF SCHEMA_ID(N'filter.schema_1') IS NULL EXEC(N'CREATE SCHEMA [filter.schema_1]');
IF SCHEMA_ID(N'filter.ignore?schema') IS NULL EXEC(N'CREATE SCHEMA [filter.ignore?schema]');

CREATE TABLE [ape_dts].[test_db_*.*].[one_pk_no_uk_1_*.*] ([f_0_*.*] int NOT NULL PRIMARY KEY, [f_1_*.*] smallint NULL, [text.*] nvarchar(80) NULL, [binary.*] varbinary(16) NULL, [decimal.*] decimal(20, 4) NULL);
CREATE TABLE [ape_dts].[test_db_*.*].[one_pk_no_uk_2_*.*] ([f_0_*.*] int NOT NULL PRIMARY KEY, [f_1_*.*] smallint NULL, [text.*] nvarchar(80) NULL, [binary.*] varbinary(16) NULL, [decimal.*] decimal(20, 4) NULL);
CREATE TABLE [ape_dts].[test_db_&.&].[one_pk_no_uk_1_&.&] ([f_0_&.&] int NOT NULL PRIMARY KEY, [f_1_&.&] smallint NULL, [text&] nvarchar(80) NULL, [binary&] varbinary(16) NULL, [decimal&] decimal(20, 4) NULL);
CREATE TABLE [ape_dts].[test_db_&.&].[one_pk_no_uk_2_&.&] ([f_0_&.&] int NOT NULL PRIMARY KEY, [f_1_&.&] smallint NULL, [text&] nvarchar(80) NULL, [binary&] varbinary(16) NULL, [decimal&] decimal(20, 4) NULL);
CREATE TABLE [ape_dts].[test_db_^.^].[one_pk_no_uk_1_^.^] ([f_0_^.^] int NOT NULL PRIMARY KEY, [f_1_^.^] smallint NULL, [text^] nvarchar(80) NULL, [binary^] varbinary(16) NULL, [decimal^] decimal(20, 4) NULL);
CREATE TABLE [ape_dts].[test_db_^.^].[one_pk_no_uk_2_^.^] ([f_0_^.^] int NOT NULL PRIMARY KEY, [f_1_^.^] smallint NULL, [text^] nvarchar(80) NULL, [binary^] varbinary(16) NULL, [decimal^] decimal(20, 4) NULL);
CREATE TABLE [ape_dts].[test_db_@.@].[one_pk_no_uk_1_@.@] ([f_0_@.@] int NOT NULL PRIMARY KEY, [f_1_@.@] smallint NULL, [text@] nvarchar(80) NULL, [binary@] varbinary(16) NULL, [decimal@] decimal(20, 4) NULL);
CREATE TABLE [ape_dts].[test_db_@.@].[one_pk_no_uk_2_@.@] ([f_0_@.@] int NOT NULL PRIMARY KEY, [f_1_@.@] smallint NULL, [text@] nvarchar(80) NULL, [binary@] varbinary(16) NULL, [decimal@] decimal(20, 4) NULL);
CREATE TABLE [ape_dts].[*.*_test_db].[one_pk_no_uk_1_*.*] ([f_0_*.*] int NOT NULL PRIMARY KEY, [f_1_*.*] smallint NULL, [text.*] nvarchar(80) NULL, [binary.*] varbinary(16) NULL, [decimal.*] decimal(20, 4) NULL);
CREATE TABLE [ape_dts].[*.*_test_db].[one_pk_no_uk_2_*.*] ([f_0_*.*] int NOT NULL PRIMARY KEY, [f_1_*.*] smallint NULL, [text.*] nvarchar(80) NULL, [binary.*] varbinary(16) NULL, [decimal.*] decimal(20, 4) NULL);
CREATE TABLE [ape_dts].[&.&_test_db].[one_pk_no_uk_1_&.&] ([f_0_&.&] int NOT NULL PRIMARY KEY, [f_1_&.&] smallint NULL, [text&] nvarchar(80) NULL, [binary&] varbinary(16) NULL, [decimal&] decimal(20, 4) NULL);
CREATE TABLE [ape_dts].[&.&_test_db].[one_pk_no_uk_2_&.&] ([f_0_&.&] int NOT NULL PRIMARY KEY, [f_1_&.&] smallint NULL, [text&] nvarchar(80) NULL, [binary&] varbinary(16) NULL, [decimal&] decimal(20, 4) NULL);
CREATE TABLE [ape_dts].[^.^_test_db].[one_pk_no_uk_1_^.^] ([f_0_^.^] int NOT NULL PRIMARY KEY, [f_1_^.^] smallint NULL, [text^] nvarchar(80) NULL, [binary^] varbinary(16) NULL, [decimal^] decimal(20, 4) NULL);
CREATE TABLE [ape_dts].[^.^_test_db].[one_pk_no_uk_2_^.^] ([f_0_^.^] int NOT NULL PRIMARY KEY, [f_1_^.^] smallint NULL, [text^] nvarchar(80) NULL, [binary^] varbinary(16) NULL, [decimal^] decimal(20, 4) NULL);
CREATE TABLE [ape_dts].[@.@_test_db].[one_pk_no_uk_1_@.@] ([f_0_@.@] int NOT NULL PRIMARY KEY, [f_1_@.@] smallint NULL, [text@] nvarchar(80) NULL, [binary@] varbinary(16) NULL, [decimal@] decimal(20, 4) NULL);
CREATE TABLE [ape_dts].[@.@_test_db].[one_pk_no_uk_2_@.@] ([f_0_@.@] int NOT NULL PRIMARY KEY, [f_1_@.@] smallint NULL, [text@] nvarchar(80) NULL, [binary@] varbinary(16) NULL, [decimal@] decimal(20, 4) NULL);
CREATE TABLE [mssql_filter.db_*_e2e].dbo.[db level.* kept] (id int NOT NULL PRIMARY KEY, value nvarchar(80) NULL);
CREATE TABLE [mssql_filter.db_1_e2e].dbo.[db level.* filtered] (id int NOT NULL PRIMARY KEY, value nvarchar(80) NULL);
CREATE TABLE [mssql_filter.ignore&db_e2e].dbo.[db level& ignored] (id int NOT NULL PRIMARY KEY, value nvarchar(80) NULL);
CREATE TABLE [ape_dts].[filter.schema_*].[schema level.* kept] (id int NOT NULL PRIMARY KEY, value nvarchar(80) NULL);
CREATE TABLE [ape_dts].[filter.schema_1].[schema level.* filtered] (id int NOT NULL PRIMARY KEY, value nvarchar(80) NULL);
CREATE TABLE [ape_dts].[filter.ignore?schema].[schema level? ignored] (id int NOT NULL PRIMARY KEY, value nvarchar(80) NULL);
GO
