DROP DATABASE IF EXISTS tls_test;
CREATE DATABASE tls_test;
CREATE TABLE tls_test.accounts (id INT NOT NULL PRIMARY KEY, value VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL);
