name: Build and upload to S3

on:
  workflow_dispatch:
    inputs:
      aws_endpoint:
        description: 'AWS S3 endpoint URL'
        required: true
        type: string
        default: https://s3.ap-northeast-1.amazonaws.com
      aws_bucket:
        description: 'AWS S3 bucket name'
        required: true
        type: string
        default: foxlake
      aws_destination_dir:
        description: 'S3 destination directory path'
        required: true
        type: string
        default: ape-dts/latest

jobs:
  build:
    name: Cross build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up rust
        uses: dtolnay/rust-toolchain@1.85.0

      - name: Setup cross-compilation
        uses: taiki-e/setup-cross-action@v1

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: s3-build-${{ hashFiles('**/Cargo.lock') }}

      - name: Build for x86_64
        run: cross build --target x86_64-unknown-linux-gnu --release

      - name: Build for aarch64
        run: cross build --target aarch64-unknown-linux-gnu --release

      - name: Copy artifacts
        run: |
          mkdir -p bin/arm64-unknown-linux-gnu bin/amd64-unknown-linux-gnu
          cp target/x86_64-unknown-linux-gnu/release/dt-main bin/amd64-unknown-linux-gnu/ape-dts
          cp target/aarch64-unknown-linux-gnu/release/dt-main bin/arm64-unknown-linux-gnu/ape-dts
          cp log4rs.yaml bin/amd64-unknown-linux-gnu/
          cp log4rs.yaml bin/arm64-unknown-linux-gnu/

      - name: Upload to s3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ inputs.aws_bucket }}
          endpoint: ${{ inputs.aws_endpoint }}
          source_dir: bin
          destination_dir: ${{ inputs.aws_destination_dir }}
