name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE*'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.svg'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE*'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.svg'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  lint:
    name: Lint & Static Checks
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          # Use a unified cache key to allow sharing across jobs
          key: lint-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Check formatting (rustfmt)
        run: cargo fmt --all --check

      - name: Run lint checks
        id: lint
        run: make lint

      - name: Run cargo check
        run: cargo check --workspace --all-targets --all-features

      - name: Summarize lint issues
        if: always()
        run: |
          echo "## 🔍 Lint Check Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # Check if there were any issues
          if [ "${{ steps.lint.outcome }}" == "failure" ]; then
            echo "❌ **Issues found during linting:**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "- **Clippy:** Found code quality issues" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "📋 **Next steps:**" >> $GITHUB_STEP_SUMMARY
            echo "1. Review the detailed logs above" >> $GITHUB_STEP_SUMMARY
            echo "2. Fix the identified issues" >> $GITHUB_STEP_SUMMARY
            echo "3. Re-run the CI to verify fixes" >> $GITHUB_STEP_SUMMARY
          else
            echo "✅ **All lint checks passed!**" >> $GITHUB_STEP_SUMMARY
          fi

  # Run unit and documentation tests
  test:
    name: Tests
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: test-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            lint-${{ runner.os }}-

      - name: Install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: Run unit tests with nextest
        run: |
          cargo nextest run \
            --workspace \
            --exclude dt-tests \
            --lib --bins \
            --no-fail-fast

      - name: Run doc tests
        run: cargo test --workspace --doc --exclude dt-tests
