name: E2E Tests

on:
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Test suite to run (optional, runs all if not specified)'
        required: false
        type: string
        default: ''
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  # Define the path to the single, consolidated Docker Compose file.
  COMPOSE_FILE: ./dt-tests/tests/docker-compose.yml

jobs:
  # This job dynamically discovers available test suites to build the test matrix.
  list-test-suites:
    name: Discover E2E Test Suites
    runs-on: ubuntu-latest
    outputs:
      suites: ${{ steps.set-matrix.outputs.suites }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Generate Test Suite Matrix
        id: set-matrix
        working-directory: ./dt-tests/tests
        run: |
          # This command lists directories, excludes 'test_runner', and formats them into a JSON array.
          SUITES=$(ls -d */ | grep -v 'test_runner/' | sed 's/\///' | jq -R . | jq -s . | jq -c .)
          echo "Discovered suites: $SUITES"
          echo "suites=$SUITES" >> $GITHUB_OUTPUT

  # This job runs the E2E tests in parallel for each discovered suite.
  # It uses a single docker-compose file and starts only the required services.
  run-e2e-tests:
    name: E2E - ${{ matrix.test-suite }}
    needs: list-test-suites
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        test-suite: ${{ fromJson(needs.list-test-suites.outputs.suites) }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cache Rust Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: integration-${{ matrix.test-suite }}-${{ runner.os }}

      - name: Install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: Start Required Services
        run: |
          if [[ -n "${{ github.event.inputs.test_suite }}" && "${{ github.event.inputs.test_suite }}" != "${{ matrix.test-suite }}" ]]; then
            echo "Skipping suite '${{ matrix.test-suite }}' as '${{ github.event.inputs.test_suite }}' was requested."
            exit 0
          fi

          # Determine which services to start based on the test suite name.
          SERVICES_TO_START=""
          case "${{ matrix.test-suite }}" in
            mysql_to_mysql)
              SERVICES_TO_START="mysql-src mysql-dst mysql-meta"
              ;;
            pg_to_pg)
              SERVICES_TO_START="postgres-src postgres-dst"
              ;;
            redis_to_redis)
              SERVICES_TO_START="redis-src redis-dst"
              ;;
            mongo_to_mongo)
              SERVICES_TO_START="mongo-src mongo-dst"
              ;;
            *)
              echo "::error::Unknown test suite '${{ matrix.test-suite }}'. No services defined."
              exit 1
              ;;
          esac

          echo "🚀 Starting services for ${{ matrix.test-suite }}: $SERVICES_TO_START"
          # Pass the determined service names to the 'docker compose up' command.
          docker compose -f $COMPOSE_FILE up --detach --wait --timeout 600 $SERVICES_TO_START
          
          echo "✅ Services are running."
          docker compose -f $COMPOSE_FILE ps

      - name: Run E2E Tests
        if: github.event.inputs.test_suite == '' || github.event.inputs.test_suite == matrix.test-suite
        run: |
          echo "🧪 Running ${{ matrix.test-suite }} E2E tests..."
          cargo nextest run \
            --package dt-tests \
            --test integration_test \
            --no-fail-fast \
            '${{ matrix.test-suite }}::' \
            -- --test-threads=1 --test-timeout 300s

      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results-${{ matrix.test-suite }}
          path: |
            target/nextest/
          retention-days: 7

      - name: Cleanup Services
        if: always()
        run: |
          echo "🧹 Cleaning up docker resources for ${{ matrix.test-suite }}..."
          if [[ ${{ job.status }} == 'failure' ]]; then
            echo "🚨 Job failed. Dumping service logs:"
            docker compose -f $COMPOSE_FILE logs --tail 200 || true
          fi
          # 'down' will intelligently stop and remove only the containers started by compose.
          docker compose -f $COMPOSE_FILE down --volumes --remove-orphans || true
